name: Bug Report
description: Report bug for this project
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please describe a problem with enough information so that it can easily be fixed.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Call '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Reproduction code
      description: Code to create a minimal reproduction.
      render: typescript

  - type: input
    id: repro-link
    attributes:
      label: Reproduction URL
      description: Use [Stackblitz](https://stackblitz.com/fork/rxjs-mbx4c6) or a git repo to show a minimal reproduction of the issue. Please also paste the example code in the "Reproduction code" section above.

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Which version of rxjs-poll are you using?
      options:
        - '2.x.x'
        - '1.x.x'
        - 'Not sure'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: Version of runtime environment, build configuration, etc, that can affect behavior.

  - type: textarea
    id: addition
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have tested with the latest version
          required: false
