name: Feature Request
description: Suggest an idea for this project
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Please make sure this feature request hasn't been already submitted by someone by looking through other open/closed issues.

  - type: dropdown
    attributes:
      multiple: false
      label: Type of Feature
      description: Select the type of feature request.
      options:
        - 'New Feature'
        - 'Documentation'
        - 'Code Refactor'
        - 'Performance Improvements'
        - 'New Test'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Problem
      description: Describe the problem this feature would solve or the use case it addresses
      placeholder: 'e.g., I need to poll an API with adaptive delays based on response data...'
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: 'e.g., Add a new strategy type that allows...'
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like links, screenshots, examples, etc.
